import Header from "@components/Header/Header";
import "../../globals.css";
import { Inter } from "next/font/google";
import AuthWrapper from "@/app/components/AuthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <div className="flex-1">{children}</div>
    </>
  );
}
