import Header from "@components/Header/Header";
import "../../globals.css";
import StoreInitializer from "@components/StoreInitializer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <StoreInitializer filter={{ nams: "surya" }} />
      <Header />
      <div className="flex-1">{children}</div>
    </>
  );
}
