import Header from "@components/Header/Header";
import "../../globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <>
      <Header />
      <div className="flex-1">{children}</div>
    </>
  );
}
